# Generated by Django 4.0.6 on 2022-07-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_advertisement_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
