# Generated by Django 4.0.6 on 2022-07-26 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0011_rename_author_id_advertisement_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='address',
        ),
    ]
